zuul:
  ignoredServices: '*'
  routes:
    noots:
      path: /noot/**
      url: http://noot-service:8091/noot
    account:
      path: /account/**
      url: http://account-service:8081/account
    trends:
      path: /hashtag/**
      url: http://hashtag-service:8071/hashtag
    follow:
      path: /follow/**
      url: http://follow-service:8061/follow