zuul:
  ignoredServices: '*'
  routes:
    noots:
      path: /noot/**
      url: http://noots-deployment:8091/noot
    account:
      path: /account/**
      url: http://authentication-deployment:8081/account
    trends:
      path: /hastag/**
      url: http://hashtag-deployment:8071/hashtag
    follow:
      path: /follow/**
      url: http://follow-deployment:8061/follow