zuul:
  ignoredServices: '*'
  routes:
    noots:
      path: /noot/**
      url: http://172.18.0.4:8091/noot
    account:
      path: /account/**
      url: http://172.18.0.5:8081/account
    trends:
      path: /hastag/**
      url: http://172.18.0.11:8071/hashtag
    follow:
      path: /follow/**
      url: http://172.18.0.3:8061/follow