zuul:
  ignoredServices: '*'
  routes:
    noots:
      path: /noot/**
      url: http://172.17.0.9:8091/noot
    account:
      path: /account/**
      url: http://172.17.0.8:8081/account
    trends:
      path: /hastag/**
      url: http://172.17.0.11:8071/hashtag
    follow:
      path: /follow/**
      url: http://172.17.0.10:8061/follow